const produk = [
    "Sabra",
    "Hewlett Packard (HP)",
    "Pillsbury",
    "Axa",
    "PUMA",
    "SodaStream",
    "Ahava",
    "Siemens",
    "Danone",
    "McDonald's",
    "Starbucks",
    "Coca-Cola",
    "Burger King",
    "Pizza Hut",
    "Papa John's",
    "Nestle",
    "Jaffa",
    "Eden",
    "Strauss",
    "Tivall",
    "Motorola",
    "Intel",
    "IBM",
    "AOL",
    "META",
    "L'Oréal",
    "Revlon",
    "Estée Lauder",
    "Kimberly-Clark",
    "M&S",
    "Timberland",
    "River Island",
    "Delta",
    "Scarlett",
    "ESQA",
    "Rose All Day",
    "Pepsi",
    "Dr. Fischer",
    "Saboon",
    "Moroccanoil",
    "Kfc",
    "Subway",
    "Rinso",
    "Molto",
    "Pepsodent",
    "Close up",
    "Sensodyne",
    "Oral-b",
    "Pantene",
    "Sunsilk",
    "Lifeboy",
    "Lux",
    "Vanish",
    "Johnsons",
    "Cif",
    "Fairy",
    "Colgate",
    "Listerine",
    "Head& shoulder",
    "Kitkat",
    "Magnum",
    "Oreo",
    "Lays",
    "Kraft",
    "Pringles",
    "Biskuat",
    "Twix",
    "Mars",
    "Doritos",
    "Cheetos",
    "Milo",
    "M&Ms",
    "Cornflakes",
    "Sariwangi",
    "Lipton",
    "Nestea",
    "Royco",
    "Knorr",
    "Maggi",
    "Aqua",
    "Vit",
    "Fanta",
    "Sprite",
    "Nescafe",
    "2 Tang",
    "Dancow",
    "Koko Krunch",
    "Nesquik",
    "Elbit Systems",
    "CAT",
    "Barclays",
    "Chevron",
    "CAF",
    "JCB",
    "Volvo",
    "TKH Security",
    "HD Hyundai",
    "HikVision",
    "Axe",
    "Bango",
    "Buavita",
    "Cif",
    "Citra",
    "Clear",
    "Clear Men",
    "Closeup",
    "Cornetto",
    "Dove",
    "Feast",
    "Glow and Lovely",
    "Hellmann's",
    "Jawara",
    "Knorr",
    "Lifebouy",
    "Lipton",
    "Love Beauty & Planet",
    "Lux",
    "Magnum",
    "Molto",
    "Paddle Pop",
    "Pepsodent",
    "Ponds",
    "Pond's Men",
    "Populaire Indonesia",
    "Rexona",
    "Rinso",
    "Royco",
    "SariWangi",
    "Bango",
    "Nivea",
    "Buavita",
    "Cif",
    "Citra",
    "Clear",
    "Clear Men",
    "Close Up",
    "Cornetto",
    "Dove",
    "Feast",
    "Glow & Lovely",
    "Hellmanns",
    "Jawara",
    "Knorr",
    "LUX",
    "Seru",
    "Simple",
    "St. Ives",
    "Sunlight",
    "Sunsilk",
    "Superpell",
    "TRESemme",
    "The Vegetarian Butcher",
    "Unilever Profesional",
    "Vaseline Men",
    "Viennetta",
    "Vixal",
    "Wall’s",
    "Wipol",
    "Zwitsal"
];

export const products = [...new Set(produk)];